version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
  # s3:
  #   image: minio/minio
  #   restart: always
  #   environment:
  #     MINIO_ACCESS_KEY: <your-access-key-id>
  #     MINIO_SECRET_KEY: <your-secret-access-key>
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - s3-data:/data

volumes:
  mongo-data:
  # s3-data:

